export const BREAKPOINT_MAX_WIDTH = {
  MOBILE_PORTRAIT: 450,
  MOBILE_LANDSCAPE: 750,
  TABLET_PORTRAIT: 1024,
  TABLET_LANDSCAPE: 1100
}

export const NEAR_ME = 'NEAR_ME';

export const NEAR_ME_ITEM = {
  id: NEAR_ME
};


export const HISTORY_ITEMS_TO_DISPLAY = 3;
export const HISTORY_MAX_TOTAL_ITEMS = 10;
