/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { OneKeySDKConfigData, SetStore, StoreProps } from "./components/onekey-sdk-store/provider";
export namespace Components {
    interface OnekeySdk {
        "config": OneKeySDKConfigData;
    }
    interface OnekeySdkAboutUs {
    }
    interface OnekeySdkDoctorItemSwipe {
        "address": string;
        "distance": string;
        "gp": string;
        "name": string;
    }
    interface OnekeySdkGlobalStore {
        "renderer": Function;
        "store": StoreProps;
    }
    interface OnekeySdkHome {
    }
    interface OnekeySdkMap {
        "defaultZoom": number;
        "locations": any[];
        /**
          * An array of locations
         */
        "mapHeight": string;
        "mapLink": string;
        "mapTileLayer": string;
        "mapWidth": string;
        "markerIcon": string;
        "markerIconCurrentLocation": string;
        "selectedLocationIdx": number;
    }
    interface OnekeySdkRoute {
        "activatedRoute": string;
        "component": string;
        "path": string;
        "store": StoreProps;
    }
    interface OnekeySdkRouter {
    }
    interface OnekeySdkRouterLink {
        "activatedRoute": string;
        "activeClass": string;
        "anchorClass"?: string;
        "anchorId"?: string;
        "anchorRole"?: string;
        "anchorTabIndex"?: string;
        "anchorTitle"?: string;
        "ariaHaspopup"?: string;
        "ariaLabel"?: string;
        "ariaPosinset"?: string;
        "ariaSetsize"?: number;
        "custom": string;
        "match": boolean;
        "setActivatedRoute": Function;
        "url": string;
    }
    interface OnekeySdkRouterStore {
        "renderer": Function;
    }
    interface OnekeySdkSearch {
        "setActivatedRoute": any;
        "setStore": any;
        "store": any;
    }
    interface OnekeySdkSearchResult {
        "setStore": SetStore;
        "store": StoreProps;
    }
}
declare global {
    interface HTMLOnekeySdkElement extends Components.OnekeySdk, HTMLStencilElement {
    }
    var HTMLOnekeySdkElement: {
        prototype: HTMLOnekeySdkElement;
        new (): HTMLOnekeySdkElement;
    };
    interface HTMLOnekeySdkAboutUsElement extends Components.OnekeySdkAboutUs, HTMLStencilElement {
    }
    var HTMLOnekeySdkAboutUsElement: {
        prototype: HTMLOnekeySdkAboutUsElement;
        new (): HTMLOnekeySdkAboutUsElement;
    };
    interface HTMLOnekeySdkDoctorItemSwipeElement extends Components.OnekeySdkDoctorItemSwipe, HTMLStencilElement {
    }
    var HTMLOnekeySdkDoctorItemSwipeElement: {
        prototype: HTMLOnekeySdkDoctorItemSwipeElement;
        new (): HTMLOnekeySdkDoctorItemSwipeElement;
    };
    interface HTMLOnekeySdkGlobalStoreElement extends Components.OnekeySdkGlobalStore, HTMLStencilElement {
    }
    var HTMLOnekeySdkGlobalStoreElement: {
        prototype: HTMLOnekeySdkGlobalStoreElement;
        new (): HTMLOnekeySdkGlobalStoreElement;
    };
    interface HTMLOnekeySdkHomeElement extends Components.OnekeySdkHome, HTMLStencilElement {
    }
    var HTMLOnekeySdkHomeElement: {
        prototype: HTMLOnekeySdkHomeElement;
        new (): HTMLOnekeySdkHomeElement;
    };
    interface HTMLOnekeySdkMapElement extends Components.OnekeySdkMap, HTMLStencilElement {
    }
    var HTMLOnekeySdkMapElement: {
        prototype: HTMLOnekeySdkMapElement;
        new (): HTMLOnekeySdkMapElement;
    };
    interface HTMLOnekeySdkRouteElement extends Components.OnekeySdkRoute, HTMLStencilElement {
    }
    var HTMLOnekeySdkRouteElement: {
        prototype: HTMLOnekeySdkRouteElement;
        new (): HTMLOnekeySdkRouteElement;
    };
    interface HTMLOnekeySdkRouterElement extends Components.OnekeySdkRouter, HTMLStencilElement {
    }
    var HTMLOnekeySdkRouterElement: {
        prototype: HTMLOnekeySdkRouterElement;
        new (): HTMLOnekeySdkRouterElement;
    };
    interface HTMLOnekeySdkRouterLinkElement extends Components.OnekeySdkRouterLink, HTMLStencilElement {
    }
    var HTMLOnekeySdkRouterLinkElement: {
        prototype: HTMLOnekeySdkRouterLinkElement;
        new (): HTMLOnekeySdkRouterLinkElement;
    };
    interface HTMLOnekeySdkRouterStoreElement extends Components.OnekeySdkRouterStore, HTMLStencilElement {
    }
    var HTMLOnekeySdkRouterStoreElement: {
        prototype: HTMLOnekeySdkRouterStoreElement;
        new (): HTMLOnekeySdkRouterStoreElement;
    };
    interface HTMLOnekeySdkSearchElement extends Components.OnekeySdkSearch, HTMLStencilElement {
    }
    var HTMLOnekeySdkSearchElement: {
        prototype: HTMLOnekeySdkSearchElement;
        new (): HTMLOnekeySdkSearchElement;
    };
    interface HTMLOnekeySdkSearchResultElement extends Components.OnekeySdkSearchResult, HTMLStencilElement {
    }
    var HTMLOnekeySdkSearchResultElement: {
        prototype: HTMLOnekeySdkSearchResultElement;
        new (): HTMLOnekeySdkSearchResultElement;
    };
    interface HTMLElementTagNameMap {
        "onekey-sdk": HTMLOnekeySdkElement;
        "onekey-sdk-about-us": HTMLOnekeySdkAboutUsElement;
        "onekey-sdk-doctor-item-swipe": HTMLOnekeySdkDoctorItemSwipeElement;
        "onekey-sdk-global-store": HTMLOnekeySdkGlobalStoreElement;
        "onekey-sdk-home": HTMLOnekeySdkHomeElement;
        "onekey-sdk-map": HTMLOnekeySdkMapElement;
        "onekey-sdk-route": HTMLOnekeySdkRouteElement;
        "onekey-sdk-router": HTMLOnekeySdkRouterElement;
        "onekey-sdk-router-link": HTMLOnekeySdkRouterLinkElement;
        "onekey-sdk-router-store": HTMLOnekeySdkRouterStoreElement;
        "onekey-sdk-search": HTMLOnekeySdkSearchElement;
        "onekey-sdk-search-result": HTMLOnekeySdkSearchResultElement;
    }
}
declare namespace LocalJSX {
    interface OnekeySdk {
        "config"?: OneKeySDKConfigData;
    }
    interface OnekeySdkAboutUs {
    }
    interface OnekeySdkDoctorItemSwipe {
        "address"?: string;
        "distance"?: string;
        "gp"?: string;
        "name"?: string;
    }
    interface OnekeySdkGlobalStore {
        "renderer"?: Function;
        "store"?: StoreProps;
    }
    interface OnekeySdkHome {
    }
    interface OnekeySdkMap {
        "defaultZoom"?: number;
        "locations"?: any[];
        /**
          * An array of locations
         */
        "mapHeight"?: string;
        "mapLink"?: string;
        "mapTileLayer"?: string;
        "mapWidth"?: string;
        "markerIcon"?: string;
        "markerIconCurrentLocation"?: string;
        "selectedLocationIdx"?: number;
    }
    interface OnekeySdkRoute {
        "activatedRoute"?: string;
        "component"?: string;
        "path"?: string;
        "store"?: StoreProps;
    }
    interface OnekeySdkRouter {
    }
    interface OnekeySdkRouterLink {
        "activatedRoute"?: string;
        "activeClass"?: string;
        "anchorClass"?: string;
        "anchorId"?: string;
        "anchorRole"?: string;
        "anchorTabIndex"?: string;
        "anchorTitle"?: string;
        "ariaHaspopup"?: string;
        "ariaLabel"?: string;
        "ariaPosinset"?: string;
        "ariaSetsize"?: number;
        "custom"?: string;
        "match"?: boolean;
        "setActivatedRoute"?: Function;
        "url"?: string;
    }
    interface OnekeySdkRouterStore {
        "renderer"?: Function;
    }
    interface OnekeySdkSearch {
        "setActivatedRoute"?: any;
        "setStore"?: any;
        "store"?: any;
    }
    interface OnekeySdkSearchResult {
        "setStore"?: SetStore;
        "store"?: StoreProps;
    }
    interface IntrinsicElements {
        "onekey-sdk": OnekeySdk;
        "onekey-sdk-about-us": OnekeySdkAboutUs;
        "onekey-sdk-doctor-item-swipe": OnekeySdkDoctorItemSwipe;
        "onekey-sdk-global-store": OnekeySdkGlobalStore;
        "onekey-sdk-home": OnekeySdkHome;
        "onekey-sdk-map": OnekeySdkMap;
        "onekey-sdk-route": OnekeySdkRoute;
        "onekey-sdk-router": OnekeySdkRouter;
        "onekey-sdk-router-link": OnekeySdkRouterLink;
        "onekey-sdk-router-store": OnekeySdkRouterStore;
        "onekey-sdk-search": OnekeySdkSearch;
        "onekey-sdk-search-result": OnekeySdkSearchResult;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "onekey-sdk": LocalJSX.OnekeySdk & JSXBase.HTMLAttributes<HTMLOnekeySdkElement>;
            "onekey-sdk-about-us": LocalJSX.OnekeySdkAboutUs & JSXBase.HTMLAttributes<HTMLOnekeySdkAboutUsElement>;
            "onekey-sdk-doctor-item-swipe": LocalJSX.OnekeySdkDoctorItemSwipe & JSXBase.HTMLAttributes<HTMLOnekeySdkDoctorItemSwipeElement>;
            "onekey-sdk-global-store": LocalJSX.OnekeySdkGlobalStore & JSXBase.HTMLAttributes<HTMLOnekeySdkGlobalStoreElement>;
            "onekey-sdk-home": LocalJSX.OnekeySdkHome & JSXBase.HTMLAttributes<HTMLOnekeySdkHomeElement>;
            "onekey-sdk-map": LocalJSX.OnekeySdkMap & JSXBase.HTMLAttributes<HTMLOnekeySdkMapElement>;
            "onekey-sdk-route": LocalJSX.OnekeySdkRoute & JSXBase.HTMLAttributes<HTMLOnekeySdkRouteElement>;
            "onekey-sdk-router": LocalJSX.OnekeySdkRouter & JSXBase.HTMLAttributes<HTMLOnekeySdkRouterElement>;
            "onekey-sdk-router-link": LocalJSX.OnekeySdkRouterLink & JSXBase.HTMLAttributes<HTMLOnekeySdkRouterLinkElement>;
            "onekey-sdk-router-store": LocalJSX.OnekeySdkRouterStore & JSXBase.HTMLAttributes<HTMLOnekeySdkRouterStoreElement>;
            "onekey-sdk-search": LocalJSX.OnekeySdkSearch & JSXBase.HTMLAttributes<HTMLOnekeySdkSearchElement>;
            "onekey-sdk-search-result": LocalJSX.OnekeySdkSearchResult & JSXBase.HTMLAttributes<HTMLOnekeySdkSearchResultElement>;
        }
    }
}
