/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { OneKeySDKConfigData } from "./core/stores/ConfigStore";
export namespace Components {
    interface OnekeySdk {
        "config": OneKeySDKConfigData;
    }
    interface OnekeySdkDoctorCard {
        "address": string;
        "distance": string;
        "gp": string;
        "name": string;
        "selected": boolean;
        "viewMode": string;
    }
    interface OnekeySdkHome {
    }
    interface OnekeySdkLoading {
    }
    interface OnekeySdkMap {
        "defaultZoom": number;
        "locations": any[];
        "mapHeight": string;
        "mapWidth": string;
        "markerIcon": string;
        "selectedLocationIdx": number;
    }
    interface OnekeySdkRoute {
        "component": string;
        "path": string;
    }
    interface OnekeySdkRouter {
    }
    interface OnekeySdkRouterLink {
        "activeClass": string;
        "anchorClass"?: string;
        "anchorId"?: string;
        "anchorRole"?: string;
        "anchorTabIndex"?: string;
        "anchorTitle"?: string;
        "ariaHaspopup"?: string;
        "ariaLabel"?: string;
        "ariaPosinset"?: string;
        "ariaSetsize"?: number;
        "custom": string;
        "url": string;
    }
    interface OnekeySdkSearch {
    }
    interface OnekeySdkSearchAddressItem {
        "activated": boolean;
        "item": any;
        "type": string;
    }
    interface OnekeySdkSearchResult {
    }
    interface OnekeySdkSwitchViewMode {
    }
}
declare global {
    interface HTMLOnekeySdkElement extends Components.OnekeySdk, HTMLStencilElement {
    }
    var HTMLOnekeySdkElement: {
        prototype: HTMLOnekeySdkElement;
        new (): HTMLOnekeySdkElement;
    };
    interface HTMLOnekeySdkDoctorCardElement extends Components.OnekeySdkDoctorCard, HTMLStencilElement {
    }
    var HTMLOnekeySdkDoctorCardElement: {
        prototype: HTMLOnekeySdkDoctorCardElement;
        new (): HTMLOnekeySdkDoctorCardElement;
    };
    interface HTMLOnekeySdkHomeElement extends Components.OnekeySdkHome, HTMLStencilElement {
    }
    var HTMLOnekeySdkHomeElement: {
        prototype: HTMLOnekeySdkHomeElement;
        new (): HTMLOnekeySdkHomeElement;
    };
    interface HTMLOnekeySdkLoadingElement extends Components.OnekeySdkLoading, HTMLStencilElement {
    }
    var HTMLOnekeySdkLoadingElement: {
        prototype: HTMLOnekeySdkLoadingElement;
        new (): HTMLOnekeySdkLoadingElement;
    };
    interface HTMLOnekeySdkMapElement extends Components.OnekeySdkMap, HTMLStencilElement {
    }
    var HTMLOnekeySdkMapElement: {
        prototype: HTMLOnekeySdkMapElement;
        new (): HTMLOnekeySdkMapElement;
    };
    interface HTMLOnekeySdkRouteElement extends Components.OnekeySdkRoute, HTMLStencilElement {
    }
    var HTMLOnekeySdkRouteElement: {
        prototype: HTMLOnekeySdkRouteElement;
        new (): HTMLOnekeySdkRouteElement;
    };
    interface HTMLOnekeySdkRouterElement extends Components.OnekeySdkRouter, HTMLStencilElement {
    }
    var HTMLOnekeySdkRouterElement: {
        prototype: HTMLOnekeySdkRouterElement;
        new (): HTMLOnekeySdkRouterElement;
    };
    interface HTMLOnekeySdkRouterLinkElement extends Components.OnekeySdkRouterLink, HTMLStencilElement {
    }
    var HTMLOnekeySdkRouterLinkElement: {
        prototype: HTMLOnekeySdkRouterLinkElement;
        new (): HTMLOnekeySdkRouterLinkElement;
    };
    interface HTMLOnekeySdkSearchElement extends Components.OnekeySdkSearch, HTMLStencilElement {
    }
    var HTMLOnekeySdkSearchElement: {
        prototype: HTMLOnekeySdkSearchElement;
        new (): HTMLOnekeySdkSearchElement;
    };
    interface HTMLOnekeySdkSearchAddressItemElement extends Components.OnekeySdkSearchAddressItem, HTMLStencilElement {
    }
    var HTMLOnekeySdkSearchAddressItemElement: {
        prototype: HTMLOnekeySdkSearchAddressItemElement;
        new (): HTMLOnekeySdkSearchAddressItemElement;
    };
    interface HTMLOnekeySdkSearchResultElement extends Components.OnekeySdkSearchResult, HTMLStencilElement {
    }
    var HTMLOnekeySdkSearchResultElement: {
        prototype: HTMLOnekeySdkSearchResultElement;
        new (): HTMLOnekeySdkSearchResultElement;
    };
    interface HTMLOnekeySdkSwitchViewModeElement extends Components.OnekeySdkSwitchViewMode, HTMLStencilElement {
    }
    var HTMLOnekeySdkSwitchViewModeElement: {
        prototype: HTMLOnekeySdkSwitchViewModeElement;
        new (): HTMLOnekeySdkSwitchViewModeElement;
    };
    interface HTMLElementTagNameMap {
        "onekey-sdk": HTMLOnekeySdkElement;
        "onekey-sdk-doctor-card": HTMLOnekeySdkDoctorCardElement;
        "onekey-sdk-home": HTMLOnekeySdkHomeElement;
        "onekey-sdk-loading": HTMLOnekeySdkLoadingElement;
        "onekey-sdk-map": HTMLOnekeySdkMapElement;
        "onekey-sdk-route": HTMLOnekeySdkRouteElement;
        "onekey-sdk-router": HTMLOnekeySdkRouterElement;
        "onekey-sdk-router-link": HTMLOnekeySdkRouterLinkElement;
        "onekey-sdk-search": HTMLOnekeySdkSearchElement;
        "onekey-sdk-search-address-item": HTMLOnekeySdkSearchAddressItemElement;
        "onekey-sdk-search-result": HTMLOnekeySdkSearchResultElement;
        "onekey-sdk-switch-view-mode": HTMLOnekeySdkSwitchViewModeElement;
    }
}
declare namespace LocalJSX {
    interface OnekeySdk {
        "config"?: OneKeySDKConfigData;
    }
    interface OnekeySdkDoctorCard {
        "address"?: string;
        "distance"?: string;
        "gp"?: string;
        "name"?: string;
        "selected"?: boolean;
        "viewMode"?: string;
    }
    interface OnekeySdkHome {
    }
    interface OnekeySdkLoading {
    }
    interface OnekeySdkMap {
        "defaultZoom"?: number;
        "locations"?: any[];
        "mapHeight"?: string;
        "mapWidth"?: string;
        "markerIcon"?: string;
        "onMarkerClick"?: (event: CustomEvent<any>) => void;
        "onSetCurrentLocation"?: (event: CustomEvent<any>) => void;
        "selectedLocationIdx"?: number;
    }
    interface OnekeySdkRoute {
        "component"?: string;
        "path"?: string;
    }
    interface OnekeySdkRouter {
    }
    interface OnekeySdkRouterLink {
        "activeClass"?: string;
        "anchorClass"?: string;
        "anchorId"?: string;
        "anchorRole"?: string;
        "anchorTabIndex"?: string;
        "anchorTitle"?: string;
        "ariaHaspopup"?: string;
        "ariaLabel"?: string;
        "ariaPosinset"?: string;
        "ariaSetsize"?: number;
        "custom"?: string;
        "url"?: string;
    }
    interface OnekeySdkSearch {
    }
    interface OnekeySdkSearchAddressItem {
        "activated"?: boolean;
        "item"?: any;
        "onSelectAddress"?: (event: CustomEvent<any>) => void;
        "type"?: string;
    }
    interface OnekeySdkSearchResult {
    }
    interface OnekeySdkSwitchViewMode {
        "onOnSwitchViewMode"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "onekey-sdk": OnekeySdk;
        "onekey-sdk-doctor-card": OnekeySdkDoctorCard;
        "onekey-sdk-home": OnekeySdkHome;
        "onekey-sdk-loading": OnekeySdkLoading;
        "onekey-sdk-map": OnekeySdkMap;
        "onekey-sdk-route": OnekeySdkRoute;
        "onekey-sdk-router": OnekeySdkRouter;
        "onekey-sdk-router-link": OnekeySdkRouterLink;
        "onekey-sdk-search": OnekeySdkSearch;
        "onekey-sdk-search-address-item": OnekeySdkSearchAddressItem;
        "onekey-sdk-search-result": OnekeySdkSearchResult;
        "onekey-sdk-switch-view-mode": OnekeySdkSwitchViewMode;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "onekey-sdk": LocalJSX.OnekeySdk & JSXBase.HTMLAttributes<HTMLOnekeySdkElement>;
            "onekey-sdk-doctor-card": LocalJSX.OnekeySdkDoctorCard & JSXBase.HTMLAttributes<HTMLOnekeySdkDoctorCardElement>;
            "onekey-sdk-home": LocalJSX.OnekeySdkHome & JSXBase.HTMLAttributes<HTMLOnekeySdkHomeElement>;
            "onekey-sdk-loading": LocalJSX.OnekeySdkLoading & JSXBase.HTMLAttributes<HTMLOnekeySdkLoadingElement>;
            "onekey-sdk-map": LocalJSX.OnekeySdkMap & JSXBase.HTMLAttributes<HTMLOnekeySdkMapElement>;
            "onekey-sdk-route": LocalJSX.OnekeySdkRoute & JSXBase.HTMLAttributes<HTMLOnekeySdkRouteElement>;
            "onekey-sdk-router": LocalJSX.OnekeySdkRouter & JSXBase.HTMLAttributes<HTMLOnekeySdkRouterElement>;
            "onekey-sdk-router-link": LocalJSX.OnekeySdkRouterLink & JSXBase.HTMLAttributes<HTMLOnekeySdkRouterLinkElement>;
            "onekey-sdk-search": LocalJSX.OnekeySdkSearch & JSXBase.HTMLAttributes<HTMLOnekeySdkSearchElement>;
            "onekey-sdk-search-address-item": LocalJSX.OnekeySdkSearchAddressItem & JSXBase.HTMLAttributes<HTMLOnekeySdkSearchAddressItemElement>;
            "onekey-sdk-search-result": LocalJSX.OnekeySdkSearchResult & JSXBase.HTMLAttributes<HTMLOnekeySdkSearchResultElement>;
            "onekey-sdk-switch-view-mode": LocalJSX.OnekeySdkSwitchViewMode & JSXBase.HTMLAttributes<HTMLOnekeySdkSwitchViewModeElement>;
        }
    }
}
